### ISSUE TITLE
do we need an 'enable clock divider' toggle

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/mpw-mb1-pcb#14]
at the moment, you have to put a jumper between clkdv and 3.3v to enable it

**Comment by mattvenn** [comment]
and would be good to visibly see it easily

**Comment by mattvenn** [comment]
can see it with a firmware change to show it on the management gpio

**Comment by psychogenic** [comment]
You're thinking just a 2-pin jumper to high for this?  And visibility: can we pwm the gpio pin at the rate of that clock, or something like that?

**Comment by mattvenn** [comment]
yes exactly, just a 2 pin jumper. ATM I have to have a wire handy to connect the clkdiv pin to 3.3v. Something like what we have for the scan chain drive select.

I've already got a firmware that shows the frequency on the gpio led. So that's already working.

**Comment by psychogenic** [comment]
Have this as a jumper, next to manual clock MOM.
![slowclk-jumper](https://github.com/TinyTapeout/tt123-demo-pcb/assets/1799255/f76c645d-0c41-4a53-b234-76c3a6df1cf9)
