### ISSUE TITLE
change oscillator to 20M?

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/mpw-mb1-pcb#15]
needs testing first

**Comment by psychogenic** [comment]
We can test by feeding in 20M and changing the clock select jump.  But did we need something with a funny duty cycle for this to work?  If so, would that be true for TT3 as well?

**Comment by mattvenn** [comment]
Yes, we did test this a bit in the bringup. TT3 has a different chain that should mean we can just use an oscillator. 
I'll check how fast we can go with a 50% duty cycle and then make a call on the oscillator for TT2

**Comment by mattvenn** [comment]
tested up to 28M, so let's go with a 20M oscillator

https://discord.com/channels/1009193568256135208/1162346245088608366/1166759290665705485

**Comment by psychogenic** [comment]
Ok, done, changed for a 20M WE osc with same footprint.

**Comment by psychogenic** [comment]
Changed to 830208220401, another Wurth IQXO-791 series osc.  It's the hi-fi version with the same footprint (only the best for my TT friends) but the 831056293 could probably do the trick as well, for a few pennies less.
