### ISSUE TITLE
feedback on v2.2.3

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/mpw-mb1-pcb#18]
* DNP memory programming header
* DNP PMOD header
* 7 seg not soldered properly on 2 of 4 boards
* board doesn't reset properly
* reset is floating
* reset should be renamed to n_reset

![image](https://github.com/TinyTapeout/tt123-demo-pcb/assets/634220/4691aae2-8af1-4ba5-a214-3da7cec5175d)

floating reset (is pulled up by internal caravel)
![TEK00018](https://github.com/TinyTapeout/tt123-demo-pcb/assets/634220/a747d7fc-ebad-4c81-9938-982e33be7ad4)

works with a 1uf cap soldered between reset and gnd:
![TEK00019](https://github.com/TinyTapeout/tt123-demo-pcb/assets/634220/871d8d9a-2016-4194-879a-39fac6cb37e1)

**Comment by psychogenic** [comment]
Have set the DNPs at Aisler.  Have the reset RC cap solution in latest rev, as well as the ~rst naming on the symbol.

**Comment by psychogenic** [comment]
Headers J1, J3 and J9 are DNPed and excluded @ aisler.  WE 7-seg footprint was different enough to warrant a new one, which I created and populated. nRST cap fix applied, and added a DNP pull-up in case we find the internal isn't around or doing the job.  Submitted as revision 11 @ aisler, closing issue.
