### ISSUE TITLE
Make it easier to remove the carrier board

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/mpw-mb1-pcb#2]
Removing the carrier is very hard. Maybe add pokey hole to push it out from the back?

**Comment by psychogenic** [comment]
Hm, could you describe your vision/requirements for this pokey hole?  This is a 2-layer board and the Pico is right under there... so what's a pokey hole that's better than just levering the thing out, but is doable without too much disruption?

**Comment by mattvenn** [comment]
updated title and comment.
the issue atm is that you can't flash it with the board in place, so every time I tried new firmware I had to lever it out
I bent the pins after a few levering outs

**Comment by psychogenic** [comment]
There's no good way to do this... I think it matters little, now that we can program the flash in place through HK SPI.  Suggest we close.
