### ISSUE TITLE
feedback on the pinout doc

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/mpw-mb1-pcb#25]
contrast of the 7-seg could be improved. 

7 seg looks a bit weird
![image](https://github.com/TinyTapeout/tt123-demo-pcb/assets/634220/845f519c-e930-4f74-927e-37c1cf9b3b07)

Follow branding guidance (TinyTapeout -> Tiny Tapeout) (saw a ref to tinytapeout in scanchain control)

Would re-write this: 
![image](https://github.com/TinyTapeout/tt123-demo-pcb/assets/634220/b1216874-112a-4d7c-8289-66ad03b9c2ea)

to:

The clock and reset buttons are debounced switches connected to inputs 0 and 1 respectively. Not all projects use this convention, but for those that do, these are convenient ways to manually single step and reset.

would rewrite the 40M clock part of this:
![image](https://github.com/TinyTapeout/tt123-demo-pcb/assets/634220/b0e76f36-b9a2-48c6-98a6-e61e9e25ec6c)

to:

which provides a 40MHz clock (20MHz for TT02 demoboards)

Rewrite this:
![image](https://github.com/TinyTapeout/tt123-demo-pcb/assets/634220/3b8502fb-4b4d-4303-ab79-33588663311b)

To use this, set the divisor with the input switches and then connect the slow clk jumper. The slow clock will automatically be provided on input 0. 

Hard to fit in, but a few examples of slow clock settings would be nice, like the min and max :
all off = 2.3kHz
all on = 9Hz

Rewrite 'as fast as scanchain can manage' here: 
![image](https://github.com/TinyTapeout/tt123-demo-pcb/assets/634220/0b85397e-0223-4268-8017-fe5bcf6f512a)

To: 10kHz for TT03 and 5kHz for TT02.

run a spellcheck on the text. I saw a few: seperation -> separation. there might be more.

**Comment by mattvenn** [comment]
Also please add the pinout diagram into this repo

**Comment by psychogenic** [comment]
All changes made, hacked up 7-seg image, pinout uploaded and in readme.

**Comment by psychogenic** [comment]
Done
