### ISSUE TITLE
TT04_BREAKOUT required before TT04 submission date

### ISSUE THREAD

**Issue by jankralx** [TinyTapeout/mpw-mb1-pcb#5]
TT03_BREAKOUT has different pinout from expected TT04 release. It would be beneficial to fix inputs, outputs, and inouts for TT04 so TT04 chip design can be optimized for new pinout.
Related to the issue https://github.com/TinyTapeout/tt-demo-pcb/issues/1

**Comment by urish** [comment]
We hope to go with the pinout suggested at TinyTapeout/tt-demo-pcb#1, but we won't have time to thoroughly review it before the TT04 deadline. If this is a show stopper for your submission, I suggest waiting for Tiny Tapeout 5 (in ~8 weeks).
